name: ty

on: [push, pull_request]

jobs:
  static-analysis:
    name: Python ty
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@main
      - name: ty
        run: uv run --extra dev ty check src tests
